export default {
  ts: "TypeScript",
  js: "JavaScript",
  python: "Python",
  sqlite: "SQLite",
  mongo: "MongoDB",
  postgreSql: "PostgreSQL",
  html: "HTML",
  css: "CSS",
  sass: "SASS",
  scss: "SCSS",
  less: "Less",
  stylus: "Stylus",
  ejs: "EJS",
  jinja: "Jinja2",
  node: "Node.js",
  vscode: "VSCode",
  nvim: "NeoVim",
  figma: "Figma",
  git: "Git & GitHub",
  xfce: "XFCE",
  react: "React",
  discordJs: "Discord.js",
  flask: "Flask",
  quart: "Quart",
  express: "Express",
  rtk: "RTK",
  zod: "Zod",
  webpack: "WebPack",
  pug: "Pug",
  gulp: "Gulp",
  next: "Next",
  deno: "Deno",
  java: "Java",
  sql: "SQL",
  mysql: "MySQL",
  javafx: "JavaFX",
  hibernate: "Hibernate ORM",
  numpy: "NumPy",
  pandas: "Pandas",
  xlsxwriter: "XlsxWriter",
  nltk: "NLTK",
  shell: "Shell",
  django: "Django",
  ml:"ML-Libraries"
};
