export default {
    discord: "discord.com/users/",
    github: "github.com/",
    figma: "",
    replit: "replit.com/@",
    stackOverflow: "stackoverflow.com/users/",
    codewars: "codewars.com/users/",
    devTo: "dev.to/",
    cssBattle: "cssbattle.dev/player/",
    codepen: "codepen.io/",
    dribble: "dribbble.com/",
    email: "mailto:",
    linkedin: "linkedin.com/in/",
    phone: "tel:",
    demo: "",
    report: "",
}